# Generated by Django 3.2 on 2022-05-05 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
